ecommerce_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: ecommerce_user
      password: ecommerce_pass
      port: 5432
      dbname: ecommerce_db
      schema: public
      threads: 4
